### ISSUE TITLE
Newbie having trouble getting my head around how things should work

### ISSUE THREAD

**Issue by favetelinguis** [jarohen/chime#12]
When code like this runs:
clojure
(def chimes (chime-ch (periodic-seq (t/now)
              (-> 5 t/seconds))))
clojure

Does this create a running statefull process that should be located as its own component in the system?

**Comment by jarohen** [comment]
Hi there - yes - chime-ch starts running as soon as it's called.

James

**Comment by favetelinguis** [comment]
Ok thanks
