### ISSUE TITLE
How to schedule multiple recurring jobs, called with a specific context?

### ISSUE THREAD

**Issue by pate** [jarohen/chime#14]
Coming from Quartzite (Quartz), how should I schedule multiple recurring "triggers", each with a particular context? Need to be able to modify or cancel these periodic schedules.

It's not clear from the documentation whether I can call `chime-at` with an infinite sequence of times. Perhaps you could add some example usages?

Specifically, I need to trigger multiple recurring jobs at regular time on certain days of the week, e.g. 9am every Tuesday, and/or 11am on Tuesdays and Wednesdays.

**Comment by jarohen** [comment]
Hi @pate - there are a few examples in the README of recurring schedules - maybe https://github.com/jarohen/chime#complex-schedules fits your use case? 

> Need to be able to modify or cancel these periodic schedules.
Cancelling's fine - `chime-at` returns a callback that, when called, will cancel the schedule. If you want to modify one, I'd cancel it and create a new one.

> It's not clear from the documentation whether I can call chime-at with an infinite sequence of times.
Yes - infinite sequences are fine

HTH :)

James
