### ISSUE TITLE
chime-at calls callback after schedule is cancelled if a previous callback overruns

### ISSUE THREAD

**Issue by dkharlan** [jarohen/chime#16]
This may be by design, but I thought it was confusing and wanted to bring it to your attention just in case.

```
(defn do-stuff [now]
  (println "starting" now)
  (Thread/sleep 7000) ;; some overrunning task
  (println "done" now))

(def cancel-stuff! (chime-at (rest (periodic-seq (now) (seconds 5))) do-stuff))
```

Timeline:

```
 0 sec -- schedule starts
 5 sec -- do-stuff call 1 starts
10 sec -- time for do-stuff call 2 put into chime-ch channel
12 sec -- do-stuff call 1 finishes, do-stuff call 2 starts
15 sec -- time for do-stuff call 3 put into chime-ch channel
16 sec -- cancel-stuff! called
17 sec -- do-stuff call 2 finishes, do-stuff call 3 starts
24 sec -- do-stuff call 3 finishes
```

Is this a bug, or the expected behavior?  I can see an argument for the latter, since `cancel-stuff!` is called **after** the next time in the schedule (and thus after it's added to `chime-at`'s internal `chime-ch` channel).  This is somewhat non-intuitive, however; generally I'd expect a job that hasn't started yet to stay that way if the schedule is cancelled.

I'm aware the README says that with `chime-at` cancelling overrunning jobs is the caller's responsibility, but this is slightly different situation.  If this is by design, you may want to update the documentation to clarify this.

Thank you!

**Comment by jarohen** [comment]
Hi Dave, thanks for raising this :) I agree, this seems counter intuitive - if the cancel function has been called before a job starts, the job shouldn't run.

I'm AFK at the moment, but will have a look into what's involved to fix this when I'm back (unless you fancy having a go? 😊)

James

**Comment by jarohen** [comment]
Hi Dave,

Have pushed v0.2.0 with this change. Thanks again for raising the issue :)

James
