### ISSUE TITLE
Extension idea - sequence of time + function + some controls

### ISSUE THREAD

**Issue by ozjongwon** [jarohen/chime#18]
Hi

I've just checked chime and it does things slightly different than what I thought.

If chime-ch takes a seq of map, which may be look like:
`(chime-ch [{:at <time1> :fn my-fn1} {:at <time2> :fn my-fn2} ...])`
then fn can be executed when time comes.

Also it may allow extra key to control fn execution when the time's already passed:
`{:at <time1> :fn fn1 :run-fn-for-passed-time? true}`

**Comment by jjsullivan5196** [comment]
@ozjongwon Not sure if you've already gotten along with some other solution, but this is already possible with core.async primitives. You can map over two channels, such as a chime-ch and a sequence of functions, and run the given function at the time. 

For instance https://clojure.github.io/core.async/#clojure.core.async/map

```clojure
(require '[clojure.core.async :as a]
             '[chime :refer [chime-ch]])

(defn from-now [seconds] 
  (.plusSeconds (Instant/now) seconds))

(def my-fns (map #(partial identity %) ["these" "come" "in" "time"]))
(def my-times (map from-now [2 7 10 20]))

(a/map #(prn "Got " (%1) " at " %2) [(a/to-chan my-fns) (chime-ch my-times)])
```
`a/map` itself will return a channel that has the result of applying a function to the values of N channels. Each channel will need to produce a value before getting a new result, and any input channel closing will close the returned channel.

Side note: this is a bit of a straw man contrivance, so make sure this works for your use case

**Comment by jarohen** [comment]
Closing for now as it's been a while. If you still have an issue with the latest release, could you re-open the issue?
