### ISSUE TITLE
Replace Joda Time with JDK's java.time

### ISSUE THREAD

**Issue by holyjak** [jarohen/chime#26]
As the [Joda-Time page states:](https://www.joda.org/joda-time/)

> Note that from Java SE 8 onwards, users are asked to migrate to java.time (JSR-310) - a core part of the JDK which replaces this project.

I can (hopefully) contribute a PR, if interested.

**Comment by jarohen** [comment]
haha - I'd considered doing the exact same after you raised your earlier PR :smile: 

yep, PR would be lovely, thanks - I'm happy to introduce a deprecation/removal of Joda time if that makes it easier
