### ISSUE TITLE
thread factory name is always "chime-"

### ISSUE THREAD

**Issue by orestis** [jarohen/chime#33]
```(format "chime-" (swap! !count inc))``` will always return "chime-" since there's missing a `%s`. Perhaps `str` should be used instead?

**Comment by jarohen** [comment]
Thanks - yep, will push a fix!

**Comment by pmonks** [comment]
Not to necro this thread, but is there a schedule for when this fix might be released?

**Comment by jarohen** [comment]
Thanks for the poke, I thought I'd released these. 0.3.3 up on Clojars :smile:

**Comment by pmonks** [comment]
Awesome - thanks @jarohen! 👍👍
