### ISSUE TITLE
Is chime-at supposed to be blocking or asynchronous?

### ISSUE THREAD

**Issue by nukep** [jarohen/chime#34]
In the README for 0.3.2, it says:
```
chime-at returns an AutoCloseable that can be closed to cancel the schedule.
```

To me, this implies that `chime-at` runs asynchronously, and that we can cancel its execution using the returned AutoCloseable. But when I run the example in the REPL, it blocks until it runs all the times in the sequence, then it returns the object (or never if it's infinite).

```clj
user=> (let [now (Instant/now)]
  #_=>   (chime/chime-at [(.plusSeconds now 2)
  #_=>                    (.plusSeconds now 4)]
  #_=>                   (fn [time]
  #_=>                     (println "Chiming at" time))))
Chiming at #object[java.time.Instant 0x1f5ffdd2 2020-08-25T00:14:32.904Z]
Chiming at #object[java.time.Instant 0x11981049 2020-08-25T00:14:34.904Z]
#object[chime.core$chime_at$reify__4951 0x77b586bf {:status :ready, :val nil}]
user=> 
```

Or perhaps I'm misunderstanding the purpose of the AutoCloseable. Does it serve a purpose after all the times have elapsed?

**Comment by jarohen** [comment]
That's strange - it is asynchronous. I see the same as you for your example, but:

```clojure
(do
  (let [now (Instant/now)]
    (chime-at [(.plusSeconds now 2)
               (.plusSeconds now 4)]
              (fn [time]
                (println "Chiming at" time))))
  (println "hello"))
```
prints 'hello' and returns immediately, followed by the 'chiming at' messages.

I wonder if the REPL is waiting for the schedule to finish before printing the result?

**Comment by jarohen** [comment]
It seems that it's the implementation of IDeref that causes the REPL to wait - removing this from the result of `chime-at` means that the REPL prints the result immediately. If the REPL is noticing that the result implements IDeref, and then implicitly deref'ing it for you, this would explain why it's waiting until the schedule's completed.
