### ISSUE TITLE
Dependency to clj-time unnecessary

### ISSUE THREAD

**Issue by dpiliouras** [jarohen/chime#40]
Hi there, 

First of all many thanks for this great library 👍  - much appreciated! Secondly, would you consider getting rid of the `clj-time` dependency, or at least making it optional (using a `require` expression as opposed to a `:require` clause)? From what I can see only `joda_time.clj` depends on it, and frankly that protocol extension can live in the README, right? 

Thanks again :)

**Comment by jarohen** [comment]
> First of all many thanks for this great library +1 - much appreciated! 

You're welcome! :smile: :pray: 

> Secondly, would you consider getting rid of the `clj-time` dependency, or at least making it optional (using a require expression as opposed to a `:require` clause)? From what I can see only `joda_time.clj` depends on it, and frankly that protocol extension can live in the README, right?

Sorry, no. It's currently a 'provided' dependency, which means that bringing in Chime doesn't bring in clj-time, so you shouldn't be seeing this as a transitive dependency of your application unless you/another library are bringing it in? Regarding the protocol extension, this is for backwards compatibility - removing it would be a breaking change, which I avoid where at all possible.

Cheers!

James
