### ISSUE TITLE
Dynamic bindings not conveyed

### ISSUE THREAD

**Issue by jimpil** [jarohen/chime#43]
One of the most annoying things about working with Java Executors is that binding-conveyance is on you. Observe this:

```clj
(def ^:dynamic *foo* :nothing)
=> #'chime.core/*foo*
(binding [*foo* :something] 
  (chime-at [(.plusSeconds (Instant/now) 1)] (fn [_] (println *foo*))))
=> #object[chime.core$chime_at$reify__1917 0x6303b429 {:status :pending, :val nil}]
:nothing ;; after 1 second
```
This comes down to going _beyond_ the language (i.e. as long as you stay within Clojure futures,agents,refs you don't need to 
worry about it). Thankfully the fix is super simple -  use `bound-fn`:  

```clj
(.schedule pool ^Runnable (bound-fn [] (task)) ...) ;; wrap task with `bound-fn`
```

Hope that helps...

```clj
(binding [*foo* :something] 
  (chime-at [(.plusSeconds (Instant/now) 1)] (bound-fn [_] (println *foo*))))
=> #object[chime.core$chime_at$reify__1917 0x1df32999 {:status :pending, :val nil}]
:something
```

**Comment by jimpil** [comment]
Or even better, use it once at the top-level `let`:

```clj
(let [pool (Executors/newSingleThreadScheduledExecutor thread-factory)
      !latch (promise)
      f (bound-fn [i] (f i))]
...
```

**Comment by jarohen** [comment]
Fixed - thanks :)

**Comment by elamje** [comment]
This seems to be connected to #45 based on the stack trace as it refers to the lines updated in this fix.

Are the callers to chime responsible for binding like above(https://github.com/jarohen/chime/issues/43#issue-774940278), or can we just call 
```clojure
(chime/chime-at (chime/periodic-seq ...))```?

**Comment by jimpil** [comment]
> This seems to be connected to #45 based on the stack trace as it refers to the lines updated in this fix.

The stacktrace will include the bound-fn that was submitted to the executor as it's now part of the call-stack. That doesn't mean it is to blame for anything - after all it's just a wrapper function. You can try `v0.3.2` VS the latest code and you chances are you won't see any difference.

> Are the callers to chime responsible for binding like above(#43 (comment)), or can we just call ...

As of [this](https://github.com/jarohen/chime/commit/d2f95118dd0f832c283a929280d46814c170f706) commit, you don't have to.

Hope this helps :+1:

**Comment by elamje** [comment]
Thanks for the clarification. 😄
