### ISSUE TITLE
periodic-seq NullPointerException

### ISSUE THREAD

**Issue by elamje** [jarohen/chime#45]
Thanks for creating chime! It's been incredibly helpful. I ran into an error running "0.3.2" and "0.3.3-SNAPSHOT". Here is the calling code:

```clojure
(defn -main
  [& args]
  (send "testing db...") ;; send text
  (chime/chime-at (chime/periodic-seq 
                   (-> (LocalTime/of 8 0 0)
                       (.adjustInto (ZonedDateTime/now (ZoneId/of "America/Chicago")))
                       .toInstant)
                   (Period/ofDays 1))
                  (send-rand) ;; send random text
                  {:on-finished (send "done chiming.")}))
```

Two things are interesting, I get the error below, but also, before this exception is thrown, it calls my chime fn `(send-rand)` and then calls `:on finished (send "done chiming")`. It should definitely not call `(send-rand)` as the `periodic-seq`is for another time.

`:not-delivered>Jan 02, 2021 8:46:29 AM chime.core invoke
WARNING: Error running scheduled fn
java.lang.NullPointerException
	at chime.core$chime_at$schedule_loop__1079$task__1083$fn__1084.invoke(core.clj:91)
	at chime.core$chime_at$schedule_loop__1079$task__1083.invoke(core.clj:90)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

Again, thanks for making this! I know it can be frustrating to just have people paste in stack traces and want help. I am hoping other people have, or will, see the same issue and this will help them.

**Comment by jimpil** [comment]
Hi,

Do `(send-rand)`/`(send "...")` return a one/zero arg functions respectively? Your code runs fine locally when I substitute both with `println`...

**Comment by elamje** [comment]
Hey, thanks for testing it on your machine. 

Mine still throws the same exception when I run with `(println "something")`, this is running 0.3.3-SNAPSHOT.

**Comment by jimpil** [comment]
Try with `(println "Chiming at" %)` as the chime-fn, and  #(println "done chiming.") as the `:on-finished` callback.

**Comment by elamje** [comment]
That is it. I was not wrapping my calls to `send-rand` in an anonymous function that accepted the `time` parameter. It wasn't clear to me from the docs and source that it had to be an anonymous function that accepted a parameter, so I changed it and it worked! Thanks so much. 

For future viewers of this issue, you need to make your callback anonymous and accept 1 parameter. Your callback cannot just be `(println "test")`, it needs to be like below:

```clojure
 (chime/chime-at (chime/periodic-seq 
                   (-> (LocalTime/of 8 0 0)
                       (.adjustInto (ZonedDateTime/now (ZoneId/of "America/Chicago")))
                       .toInstant)
                   (Period/ofDays 1))
                  (fn [time] (println time))
                  {:on-finished (fn [] (println "done chiming."))})
```
