### ISSUE TITLE
Examples assume Dates instead of Instants?

### ISSUE THREAD

**Issue by MareinK** [jarohen/chime#47]
I'm trying to use a filter on the result of `periodic-seq` like in this example in the README:

```clojure
(->> (chime/periodic-seq (-> (.adjustInto (LocalTime/of 0 0)
                                          (ZonedDateTime/now (ZoneId/of "America/New_York")))
                             .toInstant)
                         (Period/ofDays 1))

     (filter (comp #{DayOfWeek/TUESDAY DayOfWeek/FRIDAY}
                   #(.getDayOfWeek %))))
```

However when I try try example, I get this error:

`No matching field found: getDayOfWeek for class java.time.Instant`

The function seems to return Instants while the example assumes Dates. Am I doing something wrong or is there a problem with the example? Thanks!

**Comment by MareinK** [comment]
I've worked around it in a way similar to this for now:

```clojure
     (filter (comp
                   #{DayOfWeek/TUESDAY DayOfWeek/FRIDAY}
                   #(.getDayOfWeek %)
                   #(.atZone % (ZoneId/of "America/New_York"))))
```

**Comment by jarohen** [comment]
Thanks again - have updated the README :)
