### ISSUE TITLE
Drop times that have already passed

### ISSUE THREAD

**Issue by MareinK** [jarohen/chime#48]
In one of the examples in the README, it says: "Any times that have already passed will be dropped, as before" and this is the behavior that I would like in my application. However it seems that this is not the case: if I pass a time in the past to `chime-at`, the function is immediately executed with that time. For example:

```clojure
(chime/chime-at [(.minus (Instant/now) 1 (ChronoUnit/HOURS))] println)
```

This prints immediately with the time an hour in the past.

My solution for now is to manually drop input times in the past, but I'm interested to hear whether I'm misunderstanding the example text, or something else is going on.

**Comment by jarohen** [comment]
Thanks for spotting this - this was in fact a breaking change a few releases ago. Will update the README :)
