### ISSUE TITLE
chime-at API changes

### ISSUE THREAD

**Issue by AndreaCrotti** [jarohen/chime#50]
Currently the function being called by chime-at just takes the `time` as argument, and you can just pass one function.

It might be nice if chime-at would allow you to pass the time intervals and  either:
- allow you to pass the function and a list with all the arguments to use at each call
- allow you to pass just a list of functions, which would solve the above as well I guess if you just do `(map #(partial f %) arguments)`

This would allow to generate the input for chime-at more functionally.

```clojure
(def args [["first"] ["second"]])
(defn f [args] ...) 
(chime-at intervals f args)
````

or just 

```clojure
(def args [["first"] ["second"]])
(defn f [args] ...) 
(def fns (map #(partial f %) args))
(chime-at intervals fns)
````

**Comment by jarohen** [comment]
Cheers @AndreaCrotti :pray: As discussed, this probably isn't one I'd include in Chime for the time being, unless there's a groundswell of people shouting for it :smile: 

In the meantime, I've seen `Iterator` used for things like this in the past - passing `(.iterator coll)` to `f`, then calling `(.next it)` in `f` - HTH!

James
