### ISSUE TITLE
On-finished weird behaviours

### ISSUE THREAD

**Issue by AndreaCrotti** [jarohen/chime#51]
I can reproduce a behaviour that I think is weird with something like

```clojure
(chime/chime-at
  [10 20 30]
  (fn [time] (println time))
  {:on-finished (fn [] (println "one") (Thread/sleep 100) (println "two"))})
```

And what happens is that the `one` gets printed but `two` never does.

**Comment by jarohen** [comment]
Cheers @AndreaCrotti, fix on master
