### ISSUE TITLE
Error in the doc-string? 

### ISSUE THREAD

**Issue by 2food** [jarohen/chime#55]
In the doc-string of `chime-ch` there's a usage example: 
```clojure 
Usage: 

(let [chimes (chime-ch [(.plusSeconds (Instant/now) -2) ; has already passed, will be ignored.
                        (.plusSeconds (Instant/now) 2)
                        (.plusSeconds (Instant/now) 2)])]
  (a/<!! (go-loop []
           (when-let [msg (<! chimes)]
             (prn "Chiming at:" msg)
             (recur)))))
```

The comment states that the first time will be ignored because it has passed, but running this code will print all 3 times.

**Comment by jarohen** [comment]
Thanks! This was due to a breaking change in 0.3.2 but I should have caught this doc-string.

Cheers,

James
