### ISSUE TITLE
Support for times already past in `chime-at`

### ISSUE THREAD

**Issue by jonathanj** [jarohen/chime#7]
I'd like to expire independent items (the expiry date is determined ahead of time) from a database, on application startup I schedule all outstanding expiries. In some cases this can mean the expiration date has already passed, which causes this issue:

```
=> (chime-at [(-> -2 secs from-now)] (fn [t] (println "HEY")))
#<IllegalArgumentException java.lang.IllegalArgumentException: No implementation of method: :before? of protocol: #'clj-time.core/DateTimeProtocol found for class: nil>
```

Without having to first filter expiries that have already passed (and manually expire them) it would be convenient if passed schedules could be immediately called.

(I'm not sure if there is perhaps a better way of achieving this or if I missed something in the documentation.)

**Comment by vincentbernat** [comment]
I would also find the feature interesting. Otherwise, it is difficult to reliably trigger an event early in the future. For example, if I need to schedule something in 1 millisecond, it's quite possible that once `chime-at` is invoked, the event is in the past. The behaviour could be opt-in to not break any existing code.

**Comment by jarohen** [comment]
Have been thinking about this - would being able to supply the start-time solve that use case?

```clojure
(let [start-time (t/now)]
  (chime-at [(-> 1 t/millis t/from-now)] f {:start-time start-time}))
```

Chime could then use the start time provided (or default to `(now)` if it's not provided) to determine which times it would ignore. 

How does that sound?

**Comment by vincentbernat** [comment]
Yes, that would totally fix my use case.
